### Global values apply to all child ArgoCD Applications
spec:
  name: aoa-infra
  env: local-dev-test0
  project: default
  destination:
    server: https://kubernetes.default.svc
    namePrefix: ""
  source:
    repoURL: https://github.com/rcompos/app-deploy.git
    targetRevision: main
  # ### Add this finalizer ONLY if you want child apps to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  ignoreDifferencesMetadataLabels: true
  envPath: prod/forge
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - ApplyOutOfSyncOnly=true

### Applications to deploy, including overrides
apps:
  - name: temporal
    chartDir: temporal
    chartVer: v1
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - metadata/labels
      - group: batch
        kind: Job
        name: temporal-schema-*
        jsonPointers:
          - /status
          - /spec/template/spec/initContainers
          - /metadata/annotations
          - /spec/completions
          - /spec/parallelism
          - /spec/activeDeadlineSeconds
      - group: ""
        kind: pod
        name: temporal-schema-*
        jsonPointers:
          - /status
      - group: ""
        kind: Secret
        name: temporal-grafana
        jsonPointers:
          - /data/admin-password
      - group: ""
        kind: Deployment
        name: temporal-grafana
        jsonPointers:
          - /spec/template/metadata/annotations

