apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aoa-observability
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server:  https://kubernetes.default.svc
  sources:
    # Helm chart
    - repoURL: ${REPO_URL}
      targetRevision: ${TARGET_REVISION}
      path: aoa-observability/v1
      helm:
        valueFiles:
        - $values/${ENV_DIR}/${PROD_TYPE}/${CSP}/${ENV_NAME}/aoa-observability/values.yaml
    # Values files
    - repoURL: ${REPO_URL}
      targetRevision: ${TARGET_REVISION}
      ref: values
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true