#!/usr/bin/env bash

# https://kind.sigs.k8s.io/docs/user/quick-start/#installing-from-release-binaries

export DEBIAN_FRONTEND=noninteractive
apt update && apt install -y curl jq

# Dependencies: docker

# Install Kind
# For AMD64 / x86_64
[ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-amd64
# For ARM64
[ $(uname -m) = aarch64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.27.0/kind-linux-arm64
install -m 555 kind /usr/local/bin/kind
rm kind

# Install kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"
install -m 555 kubectl /usr/local/bin/kubectl
rm kubectl

# Install argocd cli
# https://github.com/argoproj/argo-cd/releases/tag/v2.14.9
curl -sSL -o argocd-linux-arm64 https://github.com/argoproj/argo-cd/releases/download/v2.14.9/argocd-linux-arm64
install -m 555 argocd-linux-arm64 /usr/local/bin/argocd
rm argocd-linux-arm64
