#!/usr/bin/env bash

# Change to the directory where this script is located
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
cd "$SCRIPT_DIR" || { echo "Error: Failed to change to script directory"; exit 1; }
echo "PWD: $(pwd)"

# Dependencies:
#   * Homebrew
#   * Docker Desktop (local only)

dependencies=("brew") # Un-managed dependencies

for dep in "${dependencies[@]}"; do
  if command -v "$dep" &> /dev/null; then
    echo "Confirmed: $dep"
  else
    echo "Error: Missing dependency: $dep"
    exit 1
  fi
done

brew update
brew install docker colima kind kubernetes-cli argocd jq go